import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by: node scripts/generate-sidebar-problems.cjs (run before build if you add new problems)
import problemIds from './src/generated/sidebarProblemIds.json';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Home',
      items: ['index'],
    },
    {
      type: 'category',
      label: 'LeetCode Problems',
      items: problemIds as string[],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
